# Generated by Django 5.0.1 on 2024-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_logo', models.CharField(max_length=90)),
                ('service_des', models.TextField()),
                ('service_img', models.CharField(max_length=50)),
                ('service_head', models.CharField(max_length=50)),
                ('service_rat', models.CharField(max_length=50)),
            ],
        ),
    ]
